=== KZsolt8704/IVO46O_XML/IVO46O_0920/IVO46O_konferencia.dtd
<!ELEMENT konferencia (cim, hallgatok, helyszin, eloado, datum)>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT hallgatok (hallgato+)>
<!ELEMENT hallgato (nev, lakcim)>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT lakcim (#PCDATA)>
<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT eloado (nev, lakcim, adoszam)>
<!ELEMENT adoszam (#PCDATA)>
<!ELEMENT datum (#PCDATA)>

=== KZsolt8704/IVO46O_XML/IVO46O_0920/IVO46O_konferencia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konferencia SYSTEM "IVO46O_konferencia.dtd">
<konferencia>
	<cim>VISZ őszi konferencia Miskolcon</cim>
	<hallgatok>
		<hallgato>
			<nev>Tóth Bálint</nev>
			<lakcim>3535 Miskolc, Szilvás utca 36.</lakcim>
		</hallgato>
	</hallgatok>
	<helyszin>Miskolci Egyetem</helyszin>
	<eloado>
		<nev>Homo Dominik</nev>
		<lakcim>3508 Miskolc, Egyetem út 1.</lakcim>
		<adoszam>123456-1-23</adoszam>
	</eloado>
	<datum>2024.11.05.</datum>
</konferencia>
