=== KZsolt8704/IVO46O_XML/IVO46O_0927/KZS_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="myType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="ea"/>
         <xs:enumeration value="gyak"/>
      </xs:restriction>
</xs:simpleType>

   <xs:element name="orarend">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="ora" minOccurs="1" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="kurzusnev" type="xs:string"/>
                     <xs:element name="idopont">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="nap" type="xs:date"/>
                              <xs:element name="tol" type="xs:time"/>
                              <xs:element name="ig" type="xs:time"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                     <xs:element name="helyszin" type="xs:string"/>
                     <xs:element name="oktato" type="xs:string"/>
                     <xs:element name="szak" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                  <xs:attribute name="type" type="myType" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

</xs:schema>

=== KZsolt8704/IVO46O_XML/IVO46O_0927/KZS_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KZS_orarend.xsd">
    <ora id="L01" type="ea">
        <kurzusnev>Adatkezelés XML-ben</kurzusnev>
        <idopont>
            <nap>2024.09.20.</nap>
            <tol>12:30</tol>
            <ig>15:50</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>III. évf. Mérnök info. (BSC)</szak>
    </ora>
    <ora id="L02" type="ea">
        <kurzusnev>Adatkezelés XML-ben</kurzusnev>
        <idopont>
            <nap>2024.09.27.</nap>
            <tol>12:30</tol>
            <ig>15:50</ig>
        </idopont>
        <helyszin>In/101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>III. évf. Mérnök info. (BSC)</szak>
    </ora>
    <ora id="L03" type="gyak">
        <kurzusnev>Adatkezelés XML-ben</kurzusnev>
        <idopont>
            <nap>2024.10.11.</nap>
            <tol>12:30</tol>
            <ig>15:50</ig>
        </idopont>
        <helyszin>In/101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>III. évf. Mérnök info. (BSC)</szak>
    </ora>
    <ora id="L04" type="gyak">
        <kurzusnev>Adatkezelés XML-ben</kurzusnev>
        <idopont>
            <nap>2024.12.06.</nap>
            <tol>12:30</tol>
            <ig>15:50</ig>
        </idopont>
        <helyszin>In/101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>III. évf. Mérnök info. (BSC)</szak>
    </ora>
</orarend>
